package com.rilodev.d2dapps.core.utils

object Constants {
    const val LOREM_IPSUM: String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae felis vitae magna pretium commodo et quis odio. Suspendisse at mollis mi. Phasellus at interdum lorem. Quisque rutrum aliquam fermentum. Nam tristique cursus neque, in hendrerit diam luctus non. Sed auctor lobortis sem, et cursus turpis vulputate ac. Curabitur at nisi ligula. Ut felis nisi, interdum vitae leo aliquet, scelerisque mattis augue. Praesent convallis enim enim, id elementum ipsum pretium quis. Aliquam non nisl non purus tincidunt congue vel venenatis arcu. Pellentesque vulputate sit amet lectus lobortis ultrices. Proin scelerisque purus ex, a aliquet quam maximus a. Cras sed semper ante. Quisque ultricies vulputate eros ut ullamcorper.\n" +
            "\n" +
            "Praesent consequat pellentesque magna, eget vestibulum enim blandit at. Nam sit amet ultricies turpis. Donec quis lorem ac quam scelerisque fringilla eget sed metus. Etiam posuere sagittis lobortis. Pellentesque viverra gravida gravida. Nam dignissim, turpis sed lobortis consequat, tortor risus gravida arcu, id lobortis tellus orci eget eros. Morbi eros eros, sodales ac erat vitae, ultricies pulvinar libero.\n" +
            "\n" +
            "Suspendisse id laoreet mauris, a pellentesque quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam auctor diam dui, sed tristique nisi pellentesque quis. Aenean tristique magna vel posuere efficitur. Nunc hendrerit aliquam scelerisque. Aliquam eu purus ex. Curabitur consectetur neque vel nunc vulputate elementum.\n" +
            "\n" +
            "In ut egestas eros, ac tempor mi. Sed eu sodales sem. Quisque bibendum nisl tellus, at hendrerit tellus blandit at. Phasellus consequat dolor at justo commodo, quis cursus ipsum malesuada. Etiam non orci vulputate, efficitur tortor vel, aliquam risus. Fusce sapien magna, interdum sed fermentum a, luctus eu tortor. Morbi tincidunt sagittis maximus. Aenean rhoncus ex eu felis pharetra, et dignissim lacus fermentum.\n" +
            "\n" +
            "Nam sagittis semper ligula, at aliquet arcu molestie sit amet. Fusce rhoncus tellus neque, vitae pulvinar libero euismod sed. Proin vitae consequat elit, ac egestas tellus. Pellentesque cursus dui porta, porttitor libero nec, dictum odio. Maecenas in lorem sit amet nunc scelerisque tristique at vel ex. Fusce nisi metus, maximus non tincidunt vitae, maximus in diam. Duis sit amet nisi sit amet elit imperdiet imperdiet non quis risus. Donec elementum tempor tellus sed porta. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean faucibus faucibus tortor, non elementum urna tempor at.\n" +
            "\n" +
            "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam vestibulum eros a sem molestie porta. Suspendisse facilisis est at arcu vestibulum ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam mattis non sem at facilisis. Cras est mi, laoreet ac malesuada quis, faucibus sed dolor. Vestibulum et volutpat mi. Nulla pellentesque varius velit eu facilisis. Morbi eget ante vitae dolor cursus volutpat eu molestie risus.\n" +
            "\n" +
            "Mauris eleifend tempus enim. Duis imperdiet risus non orci efficitur semper. Pellentesque dui urna, suscipit et eros nec, ornare molestie risus. Vestibulum sagittis imperdiet purus, eu lacinia nisl porta vel. Curabitur venenatis turpis nec magna vulputate scelerisque nec eu enim. Curabitur nec egestas metus. Etiam ultrices scelerisque lacus, sit amet dapibus leo scelerisque eget. Maecenas mollis tempus mauris, eget vehicula tellus egestas quis.\n" +
            "\n" +
            "Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec vestibulum augue at lacus bibendum facilisis. Aliquam fermentum lorem non purus congue accumsan. Proin mollis leo est, a maximus sapien gravida ut. Mauris porta venenatis lorem, sit amet interdum sem semper sed. Quisque tempus nunc id turpis luctus luctus. Cras ac mauris nisl. Curabitur ornare odio erat, nec tincidunt justo sodales non. In hac habitasse platea dictumst. Nam dapibus consectetur magna, dignissim faucibus nulla. Vestibulum dui mauris, venenatis a sodales vel, posuere ac felis. Integer et metus eu magna porta dapibus eget eget tortor. Sed convallis ex ut libero faucibus scelerisque. Mauris quis hendrerit neque.\n" +
            "\n" +
            "Mauris elementum libero eu sem sollicitudin tincidunt. Fusce at lacus commodo nisl mollis facilisis sed eget velit. Proin vulputate rhoncus mauris, auctor porta est commodo vel. Aliquam erat volutpat. Cras interdum mi ac aliquam lacinia. Fusce viverra leo sapien, in pharetra mauris gravida eu. Praesent a mauris eros. Nam vehicula laoreet velit sed vulputate. Suspendisse a mi ut lacus molestie bibendum a a diam. Maecenas faucibus est eu luctus consequat. Pellentesque ut velit commodo, pretium purus quis, viverra nisl. Mauris eu elementum tellus. Integer lobortis leo enim, eu vulputate dolor scelerisque sit amet. Cras sollicitudin eget felis ac hendrerit. Integer malesuada risus vitae ex molestie, eget porta ipsum facilisis.\n" +
            "\n" +
            "Nullam at elit neque. Cras eget sollicitudin est. Etiam sapien elit, consectetur vulputate tortor sit amet, fermentum iaculis mi. Maecenas nec purus eu dui auctor semper. In laoreet, elit eu pulvinar suscipit, erat tellus vestibulum lacus, sit amet interdum diam sem eget massa. Ut commodo at eros eget aliquet. Donec non porttitor neque. Ut eu dictum tellus. Donec finibus ornare diam at suscipit. Phasellus blandit lectus eu malesuada malesuada.\n" +
            "\n" +
            "Integer efficitur mattis sapien. Etiam ultrices lacinia lacinia. Proin urna sapien, gravida in ornare in, iaculis et mi. Cras eget massa non mauris pretium ornare. Sed quis dui non erat suscipit pulvinar vel in neque. Suspendisse nunc urna, vehicula vitae venenatis a, mollis at turpis. Aliquam erat volutpat. Mauris venenatis consectetur augue, at commodo purus ornare eget. Donec hendrerit, sem at cursus posuere, magna enim vehicula risus, quis consequat sapien nisl sit amet eros. Fusce maximus, sem sit amet ornare mollis, leo magna feugiat justo, et rutrum enim orci nec ex. Fusce volutpat eros in est ullamcorper, sed mollis nisl porta. Etiam in velit molestie urna ultrices blandit. Pellentesque tincidunt purus quis facilisis feugiat.\n" +
            "\n" +
            "Phasellus et tortor elementum, lobortis magna id, malesuada odio. Vestibulum at bibendum velit, at sodales eros. Praesent rutrum arcu orci, at imperdiet ex laoreet bibendum. Pellentesque bibendum gravida pellentesque. Mauris luctus neque convallis auctor placerat. Quisque tincidunt dignissim velit, at faucibus nisl convallis vitae. Maecenas tincidunt fringilla eros, tincidunt pretium eros scelerisque nec. Nam at ullamcorper dui, ac porttitor nisi. Aliquam semper, ligula ac eleifend accumsan, nulla magna ornare purus, at ornare turpis eros ut augue. Suspendisse fermentum in turpis quis venenatis. Quisque congue lectus ac massa finibus, id mollis ex mollis.\n" +
            "\n" +
            "Aliquam vel ornare nisl. Maecenas gravida pharetra nunc, non pharetra nulla finibus eu. Mauris imperdiet quis dolor nec finibus. Nullam risus nibh, aliquam in augue auctor, fermentum malesuada nibh. Nulla auctor at libero et tristique. Vestibulum cursus viverra libero cursus iaculis. Curabitur eu rhoncus dui, a aliquet ex.\n" +
            "\n" +
            "Nulla facilisi. Sed quis cursus lectus, in dictum velit. Curabitur sit amet consectetur enim. Sed viverra ultrices metus vitae condimentum. Nullam dignissim egestas tincidunt. Integer mauris justo, porta vitae dignissim non, lobortis non arcu. Suspendisse potenti.\n" +
            "\n" +
            "Phasellus aliquet tempor ultricies. Suspendisse accumsan maximus enim, eget imperdiet mauris molestie ut. Nulla facilisi. Ut consectetur sapien ac dolor blandit accumsan eu sed nisl. Donec id odio sed nunc condimentum tempor. Pellentesque a euismod sem. Sed et nulla ut sem iaculis varius. Cras ullamcorper, mauris ut imperdiet elementum, magna dui ornare ligula, vel fringilla est ligula quis ex. Morbi vel vestibulum dui. Nunc in nibh ut neque convallis placerat. Suspendisse venenatis massa non luctus placerat. Maecenas lobortis congue faucibus.\n" +
            "\n" +
            "Aenean nec bibendum ante. Fusce sed ipsum a tellus egestas cursus vitae quis sapien. In dictum, dolor a feugiat vehicula, lorem urna aliquam magna, at feugiat tellus dolor at massa. Nunc posuere commodo fringilla. Phasellus scelerisque ullamcorper rhoncus. Nulla scelerisque ultricies ex sed mollis. Sed dolor ligula, lobortis at elementum ac, dignissim in est. Proin accumsan ullamcorper purus, in feugiat diam accumsan id. Donec ultricies neque est, feugiat sollicitudin mi commodo ac. Aliquam sodales nunc gravida est blandit pharetra. Nulla scelerisque cursus arcu, eu euismod felis eleifend sit amet. Proin massa erat, imperdiet vel ullamcorper ac, molestie at lectus. Aliquam vel efficitur lectus. Duis commodo neque dui, a aliquet ligula mattis eu. Mauris auctor orci arcu, at vestibulum orci luctus eu.\n" +
            "\n" +
            "Nullam rhoncus odio in diam finibus, in interdum urna tempor. Mauris at nulla erat. Suspendisse sagittis ligula non velit ultricies, et dictum orci facilisis. Quisque facilisis quis ipsum id auctor. Nulla et mi et est mattis feugiat ut in ante. Phasellus sit amet tortor ac augue condimentum condimentum. Donec posuere quis metus non facilisis. Cras auctor, dui in faucibus egestas, dui enim imperdiet risus, ac faucibus diam leo fermentum ipsum. Sed hendrerit justo at purus faucibus gravida. Maecenas ipsum turpis, venenatis ut porta id, tempus in tellus. Sed tincidunt fringilla quam eu pulvinar. Aenean congue, libero et posuere egestas, eros odio volutpat libero, et interdum ipsum tortor fringilla diam. Proin ante erat, eleifend sit amet justo eu, finibus rhoncus purus.\n" +
            "\n" +
            "Nullam faucibus iaculis venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce sem tortor, feugiat non hendrerit vel, vulputate eget nulla. Donec a rhoncus lacus, ut viverra dui. Aliquam erat volutpat. Pellentesque non erat id mauris aliquam finibus. Donec quam erat, consectetur ut justo mollis, tempus dignissim justo. Curabitur rutrum mollis eros, id pellentesque est interdum vel. Duis vehicula nisi nisi, vel elementum tellus vulputate at.\n" +
            "\n" +
            "Fusce egestas quis leo eu vehicula. Vestibulum molestie pretium dolor, vel mattis tellus porttitor eget. Donec sit amet placerat tellus, quis congue ligula. Nam tortor quam, finibus vitae massa a, bibendum dictum ipsum. Aliquam sagittis tristique ultricies. Praesent in lacus sit amet ex hendrerit suscipit. Praesent ac enim mi. Donec vulputate velit sit amet orci congue lacinia. Nunc justo sapien, tempus ut rhoncus in, finibus eget leo. Mauris ultricies nec ante sit amet sollicitudin. Nunc luctus vestibulum maximus. Sed sagittis suscipit elit, et laoreet metus molestie sed. Pellentesque vehicula rhoncus nisl, quis hendrerit tortor ultricies vel. Phasellus varius ac lectus eu fringilla. Vivamus odio leo, ultrices eget massa id, posuere dapibus arcu.\n" +
            "\n" +
            "Donec in diam eu urna laoreet rhoncus. Sed in egestas leo. Donec posuere velit quis interdum sagittis. Etiam eu ultricies lorem. Donec malesuada quam eu dolor commodo, luctus egestas magna bibendum. Ut hendrerit dolor commodo, dapibus turpis vel, semper mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;"

    const val USERS_COLLECTION = "users"
    const val TASK_COLLECTION = "tasks"

    const val DATETIME_FORMATTER_DD_MM_YYYY = "dd-MM-yyyy'T'HH:mm:ss"
    const val DATE_FORMATTER_DD_MMM_YYYY = "dd MMM yyyy"
    const val TIME_FORMATTER_HH_MM = "HH:mm"
}